EXPERIMENT:
    NAME: 'HDTF_FULL'
    TIME: '20250901_1700'

FLAME_DRIVE_MODEL:
    NAME: 'FlameDriveAvatar'
    TASK: 'FlameDriveGaussian'

AUDIO_DRIVE_MODEL:
    NAME: 'AudioDriveAvatar'
    TASK: 'AudioDriveGaussian'
    AUDIO_EXTRACTOR: 'hubert'

FLAME_DRIVE_OPTIMIZE:
    NAME: 'Adam'
    LR_DECAY_RATE: 0.1
    LR_DECAY_ITER: 200000
    LEARNING_RATE: 1.0e-4

AUDIO_DRIVE_OPTIMIZE:
    NAME: 'Adam'
    LR_DECAY_RATE: 0.1
    LR_DECAY_ITER: 200000
    LEARNING_RATE: 1.0e-4

FLAME_DRIVE_TRAIN:
    BATCH_SIZE: 4
    TRAIN_ITER: 200000
    CHECK_INTERVAL: 1000

AUDIO_DRIVE_TRAIN:
    BATCH_SIZE: 2
    TRAIN_ITER: 200000
    CHECK_INTERVAL: 1000